### ISSUE TITLE
UMKC Team should review feedback on your project given by ABA Techshow plenary!

### ISSUE THREAD

**Issue by dazzaji** [collabx/IDASH#6]

**Comment by zmon** [comment]
URL to the talk https://youtu.be/HZPMpWz-0dc Evan is at the 1:19 mark.

**Comment by zmon** [comment]
We need to ask if anyone knows of code that implements a IdP that would be good to use for a Hackathon?

**Comment by EvanAbsher** [comment]
1. Unclear is good feedback. I didn't know the context of the presentation. 
2. I wish we would have been there. I would have been able to explain it better. 
3. Ok. Most of this feedback is good, but it stems from poor explanation, I blame myself. 
4. I think we can answer the feedback on this during the hangout. 
5. I will put my answers on the wiki under a new page called Appathon

**Comment by EvanAbsher** [comment]
The below is at the IDASH wiki, https://github.com/collabx/IDASH/wiki/APPATHON 

Plenary Feedback - 
1. Uhhh..........

A1. I get it. I gave no background because I was totally unaware of the context of the presentation. I thought I was presenting to people working with OAuth2 already. I didn't know this was a pitch to attorneys who are lay people in this area. I will upload and send out a different video later today that will respond directly to the feedback from the plenary. 
1. Will this store all my ID in one place? 

A2. No. The current institutions that house that data will continue to to house that data, the Municipal IDP will simply be the gate keeper to this information. As it stands now each of those institutions have an outward facing portal so that people can acquire the data housed within. With Muni IDP these institution would jettison their individual outward facing portal (i.e. no more user name and password screens) and instead use the IDP as a single point of contact with the public. The IDP will NOT house the data but be allowed to access the information because the institutions trust the IDP, the Citizen trusts the IDP and the Client (third party website) trusts the IDP. 
1. In the use case of the Employee Liquor Permit Application (ELPA) how does that look? The person who said, "[w]ill the IDP basically be able to say yes or no to my application?" is EXACTLY RIGHT on the nose. With the IDP the applicant will sign on to the Regulated Industries application page. There will be a notice of something like the following; 
   
   ```
                          HI WELCOME TO KANSAS CITY'S DEPARTMENT REGULATED INDUSTRIES 
                                    APPLICATION FOR AN EMPLOYEE LIQUOR PERMIT
   ```

Please note that when you click the agree button below you are authorizing the discovery and verification of the following data;
- Name
- Address
- Birthdate
- Phone Number
- Email Address 
- Dangerous Offender Status
- Felony Status
  
  ```
                               -----------------------------------
                               |   I AGREE TO THE AUTHORIZATION   |
                               ------------------------------------
  ```

Once the person hits that button their application is instantly authorized and the PERMIT AND THE PERMIT NUMBER are recorded with the department NOT the data within the application. Here is what a successful application would look like; 

```
                 CONGRATULATIONS!! YOU SUCCESSFULLY APPLIED FOR AN EMPLOYEE LIQUOR PERMIT!!!
```

Here is your permit number: 1239084u238y50923ir-23i-4u23804y230u4ei-23ir0923ur9-23irj230ij230i3-0i

Here a few things that may cause your license to be revoked or suspended:

1
2
3
4
5
6
7
8
9
10

or whatever you want to put in there. 

Is this making sense?

**Comment by EvanAbsher** [comment]
http://iddataweb.com/?page_id=505 

The above is a link to a very detailed diagram of what the network would look like, except instead of Google or PayPal acting as the IdP it would be the Municipality.

**Comment by dseacord17** [comment]
Regarding the first comment about the lack of clarity, I thought discussion of the use-case gave Evan's presentation a refreshing concreteness--it wasn't just "think of what you can do" but "this is what we will do." If the audience had no frame-of-reference on the technology though, I can understand the gentleman's confusion. 

I had a hard time making out the exchange between Michael and the panelist(s), but on the subject of the "single repository of individual data" bit, I think it's possible to explain our non-reliance of that in a fairly simple way under our use case (simple for someone with legal training to understand, anyway): 

Currently, various people or agencies have to be consulted manually for each particular application, meaning that the applicant is subject to individual scrutiny by everyone coming into contact with his or her application. Our Municipal ID would allow that consultation to occur in a completely automated way--the same parties are involved, but the data necessary to complete the application can be accessed without putting the applicant into anyone's direct gaze. The parties who provide that data are members of a "Trusted Civic Federation," to use Paul's term from our discussion yesterday. They get the advantage of being able to jettison their outward-facing user interface (as Evan explained above); the user gets the advantage of greater anonymity, convenience, and speed of response; his would-be employer at the restaurant or bar doesn't have to assume the risk that new hires, working on temporary permits, will be denied the full permit (because the yes/no response can be automatic); and the city is both able to dispense with its maintenance of an office and staff to perform a simple, routine function, and to advance its basic civic function--to promote the interests, rights, and welfare of its citizens under the law.

I realize literally nothing I said in that long paragraph is news to anyone following this thread, but having not seen a layman's description, I hoped it might be helpful for me, as the least technically knowledgeable member of the team, to put forward a way to describe the process as I understand it so similarly situated listeners can get a basic grip on the project. After that, being walked through that detailed diagram would be a lot easier.

(Also, if I'm misstating any aspect of how the project works under our use-case, please correct me.)

**Comment by zmon** [comment]
I think our problem was not understanding the audience, which has already been said.  Doug I like your third paragraph, and that is probably what they were looking for, very hight level.

I could not tell if the diagram was shown to the audience, which contained to much detail for them.

Just my 2c.

**Comment by dazzaji** [comment]
(just scanned this.  nice use of github you guys.  and...especially love that after a good chat on the issue, it's marked "issue closed" but - here is the extra goodness - you can go back anytime and review the stuff said, the reasonng, the links, etc and if needed can even re-open the issue.  github is good.  github is great.  github doth rocketh.)

**Comment by dazzaji** [comment]
Evan - I think this is a closed issue now.  It is ok for a comment on a closed issue.  It just means a comment was made on an issue that is closed.  Issues that are closed are best kept closed unless opening again is needed.  when each team member comments they have reviewed the aba feedback then this issue is literally closed.  it is a nice system that allows anyone to view "open tickets" and just see what work remains to be done.  it's up to your team to make the call to open or close any ticket that applied to you.  I recommend closing this one.
